### ISSUE TITLE
I need a Universal Render Pipeline Version Animation Sample!!!Thank you !!!

### ISSUE THREAD

**Issue by cdm456852** [Unity-Technologies/Unity.Animation.Samples#1]
I need a Universal Render Pipeline Version Animation Sample!!!Thank you !!!

**Comment by nicolasgramlich** [comment]
I managed to port it over to the Universal Render Pipeline with limited success after eventually finding a package combination that works and several (voluntary and involuntary) Unity restarts, to convince the compiler that the scripts are correct! 🕺 

Packages:
```
{
  "dependencies": {
    "com.unity.2d.sprite": "1.0.0",
    "com.unity.ads": "2.0.8",
    "com.unity.analytics": "3.3.4",
    "com.unity.animation": "0.2.16-preview.5",
    "com.unity.burst": "1.2.0",
    "com.unity.collab-proxy": "1.2.16",
    "com.unity.ide.rider": "1.1.4",
    "com.unity.ide.vscode": "1.1.3",
    "com.unity.jobs": "0.2.3-preview.9",
    "com.unity.render-pipelines.universal": "7.1.7",
    "com.unity.rendering.hybrid": "0.3.2-preview.17",
    "com.unity.test-framework": "1.1.9",
    "com.unity.test-framework.performance": "2.0.6-preview",
    "com.unity.textmeshpro": "2.0.1",
    "com.unity.timeline": "1.2.9",
    "com.unity.ugui": "1.0.0",
    "com.unity.modules.ai": "1.0.0",
    "com.unity.modules.androidjni": "1.0.0",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.assetbundle": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.cloth": "1.0.0",
    "com.unity.modules.director": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.screencapture": "1.0.0",
    "com.unity.modules.terrain": "1.0.0",
    "com.unity.modules.terrainphysics": "1.0.0",
    "com.unity.modules.tilemap": "1.0.0",
    "com.unity.modules.ui": "1.0.0",
    "com.unity.modules.uielements": "1.0.0",
    "com.unity.modules.umbra": "1.0.0",
    "com.unity.modules.unityanalytics": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
    "com.unity.modules.unitywebrequestaudio": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
    "com.unity.modules.unitywebrequestwww": "1.0.0",
    "com.unity.modules.vehicles": "1.0.0",
    "com.unity.modules.video": "1.0.0",
    "com.unity.modules.vr": "1.0.0",
    "com.unity.modules.wind": "1.0.0",
    "com.unity.modules.xr": "1.0.0"
  }
}
```

Limitations:
 * Currently `unlit` only (I've never used Shader Graph before, so I converted the `Basic_Vertex_Skinning.shadergraph` to an unlit version)
 * All meshes seem to animate "in sync" and can't figure out for my life why that is :'( 
   * I was able to get them to animate "out of sync" when "dropping in" my assets to the HDRP `TwoClipsAndMixer` example.
 * Still no texturing (See #2)

The frustration is steadily growing, mostly due to the slow turnaround time and Unity crashes bugs with the beta `2109.3.0f5` and the preview packages. So I'll probably give up for now until things mature a little more :)

Big thanks for creating these examples in the first place btw! @oldio

![image](https://user-images.githubusercontent.com/287060/72782190-03be4f80-3bd8-11ea-9712-6a45c4151a3e.png)
![image](https://user-images.githubusercontent.com/287060/72782237-19cc1000-3bd8-11ea-909b-4826cd9dca36.png)

**Comment by oldio** [comment]
Hi and thanks for the comments/feedback.

A URP pipeline is in the works but as specified in the README the current version only works with HDRP. There's a bit of work to do on our side to support instanced matrices for GPU skinning in URP.
Otherwise duly noted, we can definitely provide an example with texturing next time around. This is actually something you can already do in the shading graph by passing in a proper color coming from a texture. There's a few tutorials related to the shader graph you can follow for help:
https://www.youtube.com/watch?v=V5XFrIhLpGQ
You just need to make sure that the vertex data (positions/normals/tangents) are coming from the linear blend skinning node.

Again, this is an early preview of Dots.Animation, we know the API is still a bit rough but our goal is to make things a lot more simple to do in the near term.

**Comment by cdm456852** [comment]
> Hi and thanks for the comments/feedback.
> 
> A URP pipeline is in the works but as specified in the README the current version only works with HDRP. There's a bit of work to do on our side to support instanced skin matrices for GPU skinning in URP.
> Otherwise duly noted, we can definitely provide an example with texturing next time around. This is actually something you can already do in the shading graph by passing in a proper color coming from a texture. There's a few tutorials related to the shader graph you can follow for help:
> https://www.youtube.com/watch?v=V5XFrIhLpGQ
> You just need to make sure that the vertex data (positions/normals/tangents) are coming from the linear blend skinning node.
> 
> Again, this is an early preview of Dots.Animation, we know the API is still a bit rough but our goal is to make things a lot more simple to do in the near term.

Can you tell us the exact release time of this urp animation? Like One week later or one month later.

**Comment by nicolasgramlich** [comment]
After dipping my toes into Shader Graph the other week, I was able to get a textured example in URP to work (literally just had to hook in that texture).

![image](https://user-images.githubusercontent.com/287060/73720230-53bc0c80-46d6-11ea-8bf9-6c77b91557d5.png)

I can get ≈2500 Units to animate (simple lit, physics bodies (cylinders), no shadows, 1M triangles, SRP Batcher `disabled`, Dynamic Batching `enabled` (but doesn't seem to work)) at 30FPS in the Editor (probably some more when building the actual app)
![Screen Shot 2020-02-03 at 10 38 07 PM](https://user-images.githubusercontent.com/287060/73720103-0b9cea00-46d6-11ea-8524-e67aed740407.png)

(Closeup with shadows enabled)
![Screen Shot 2020-02-03 at 10 39 04 PM](https://user-images.githubusercontent.com/287060/73720101-0b9cea00-46d6-11ea-92c0-d9efcb427531.png)

Poking around in the Entity Debugger it looks like every single rig is animated separately, they just happen to be "in sync" because they start at exactly the same time.
![Screen Shot 2020-02-03 at 10 38 14 PM](https://user-images.githubusercontent.com/287060/73720102-0b9cea00-46d6-11ea-93c5-d6efd16b7feb.png)

My machine:
![image](https://user-images.githubusercontent.com/287060/73720459-d47b0880-46d6-11ea-95b8-bccdb292e3d4.png)

Overall I'm happy with the performance :)

Unfortunately I can't get the units to render on Android (they just don't show up) due to this error: `"Loading Entity Scene failed because the entity header file could not be found"`

It seems to be related to loading the subscene with the spawner in it, which I'm determined to figure out 💪

**Comment by cdm456852** [comment]
> After dipping my toes into Shader Graph the other week, I was able to get a textured example in URP to work (literally just had to hook in that texture).
> 
> ![image](https://user-images.githubusercontent.com/287060/73720230-53bc0c80-46d6-11ea-8bf9-6c77b91557d5.png)
> 
> On my Macbook I can get ≈2500 Units to animate (simple lit, physics bodies (cylinders), no shadows, 1M triangles, SRP Batcher `disabled`, Dynamic Batching `enabled` (but doesn't seem to work)) at 30FPS in the Editor (probably some more when building the actual app)
> ![Screen Shot 2020-02-03 at 10 38 07 PM](https://user-images.githubusercontent.com/287060/73720103-0b9cea00-46d6-11ea-8524-e67aed740407.png)
> 
> (Closeup with shadows enabled)
> ![Screen Shot 2020-02-03 at 10 39 04 PM](https://user-images.githubusercontent.com/287060/73720101-0b9cea00-46d6-11ea-92c0-d9efcb427531.png)
> 
> Poking around in the Entity Debugger it looks like every single rig is animated separately, they just happen to be "in sync" because they start at exactly the same time.
> ![Screen Shot 2020-02-03 at 10 38 14 PM](https://user-images.githubusercontent.com/287060/73720102-0b9cea00-46d6-11ea-93c5-d6efd16b7feb.png)
> 
> My machine:
> ![image](https://user-images.githubusercontent.com/287060/73720459-d47b0880-46d6-11ea-95b8-bccdb292e3d4.png)
> 
> # Android
> ## Pixel XL (2016 flagship phone)
> 30 FPS with 400 units, simple lit, physics bodies (cylinders), no shadows
> ![Screenshot_20200203-234938](https://user-images.githubusercontent.com/287060/73724499-5885be00-46e0-11ea-9f0b-90c738fde15b.png)
> 
> ## Pixel 4 XL (2019 flagship phone)
> Going to test on this one tomorrow, but pretty sure I can get 90 FPS :)
> 
> Overall I'm happy with the performance :)

I just did it all over again with what you described,But it did not work,Can you describe the whole process more specifically?

**Comment by nicolasgramlich** [comment]
> I just did it all over again with what you described,But it did not work,Can you describe the whole process more specifically?

Hm, what's not working? How I got it to work initially is basically opening my project and this one next to each other and comparing every single component and values side-by-side until the errors were gone.

Do you have a screenshot of what's not working for you rn? I'll try to respond in a timely manner :)

**Comment by oldio** [comment]
> After dipping my toes into Shader Graph the other week, I was able to get a textured example in URP to work (literally just had to hook in that texture).
> 
> ![image](https://user-images.githubusercontent.com/287060/73720230-53bc0c80-46d6-11ea-8bf9-6c77b91557d5.png)
> 
> On my Macbook I can get ≈2500 Units to animate (simple lit, physics bodies (cylinders), no shadows, 1M triangles, SRP Batcher `disabled`, Dynamic Batching `enabled` (but doesn't seem to work)) at 30FPS in the Editor (probably some more when building the actual app)
> ![Screen Shot 2020-02-03 at 10 38 07 PM](https://user-images.githubusercontent.com/287060/73720103-0b9cea00-46d6-11ea-8524-e67aed740407.png)
> 
> (Closeup with shadows enabled)
> ![Screen Shot 2020-02-03 at 10 39 04 PM](https://user-images.githubusercontent.com/287060/73720101-0b9cea00-46d6-11ea-92c0-d9efcb427531.png)
> 
> Poking around in the Entity Debugger it looks like every single rig is animated separately, they just happen to be "in sync" because they start at exactly the same time.
> ![Screen Shot 2020-02-03 at 10 38 14 PM](https://user-images.githubusercontent.com/287060/73720102-0b9cea00-46d6-11ea-93c5-d6efd16b7feb.png)
> 
> My machine:
> ![image](https://user-images.githubusercontent.com/287060/73720459-d47b0880-46d6-11ea-95b8-bccdb292e3d4.png)
> 
> # Android
> ## Pixel XL (2016 flagship phone)
> 30 FPS with 400 units, simple lit, physics bodies (cylinders), no shadows
> ![Screenshot_20200203-234938](https://user-images.githubusercontent.com/287060/73724499-5885be00-46e0-11ea-9f0b-90c738fde15b.png)
> 
> ## Pixel 4 XL (2019 flagship phone)
> Going to test on this one tomorrow, but pretty sure I can get 90 FPS :)
> 
> Overall I'm happy with the performance :)

Great work @nicolasgramlich ! Although I think you might be taking a performance hit because you may not go through the GPU instancing pipeline. To answer your question, we are planning on making a URP experimental skinning pipeline available around GDC. Hopefully you can put your hands on it then.

Note that we also just pushed another update (0.3.0-preview.7), this has quite a few improvements namely better dots component integration with our animation graph evaluator and a data layout that is more SIMD friendly. This should translate better performances overall.

**Comment by nicolasgramlich** [comment]
> Great work @nicolasgramlich ! Although I think you might be taking a performance hit because you may not go through the GPU instancing pipeline. To answer your question, we are planning on making a URP experimental skinning pipeline available around GDC. Hopefully you can put your hands on it then.

Awesome, that's barely a month away. I can't wait! :)

> Note that we also just pushed another update (0.3.0-preview.7), this has quite a few improvements namely better dots component integration with our animation graph evaluator and a data layout that is more SIMD friendly. This should translate better performances overall.

I'll check it out later and see if performance changed!

**Comment by nicolasgramlich** [comment]
I just checked out the repo. Great work on restructuring the examples, that'll help a lot of people! 👏  (@cdm456852 check out the [MyFirstAnimationClip](https://github.com/Unity-Technologies/Unity.Animation.Samples/tree/14ece9d3c953cc32c2c0f2ae196140a4ae80455c/UnityAnimationHDRPExamples/Assets/Scenes/Examples/MyFirstAnimationClip) example! )

For my project it was basically a drop in replacement, which was nice :)

Regarding performance (in the editor, I'll check on Android later): It seems about roughly the same.
I'll also try to make a direct comparison, with only animations (no physics, no custom systems enabled) :)

**Comment by nicolasgramlich** [comment]
@oldio how would I figure out the GPU instancing issue you raised?

Also here the new performance benchmark on `0.3.0-preview.7`:

# Pixel XL (≈40FPS)
![Screenshot_20200211-210223](https://user-images.githubusercontent.com/287060/74304870-12011680-4d13-11ea-8345-273f62dd4e65.png)

# Pixel 4 XL (>90FPS)
![Screenshot_20200211-210244](https://user-images.githubusercontent.com/287060/74304866-11688000-4d13-11ea-9d7b-a45ad68154bc.png)

**Comment by cdm456852** [comment]
> @oldio I just checked out the repo. Great work on restructuring the examples, that'll help a lot of people! 👏 (@cdm456852 check out the [MyFirstAnimationClip](https://github.com/Unity-Technologies/Unity.Animation.Samples/tree/14ece9d3c953cc32c2c0f2ae196140a4ae80455c/UnityAnimationHDRPExamples/Assets/Scenes/Examples/MyFirstAnimationClip) example! )
> 
> For my project it was basically a drop in replacement, which was nice :)
> 
> Regarding performance (in the editor, I'll check on Android later): It seems about roughly the same.
> I'll also try to make a direct comparison, with only animations (no physics, no custom systems enabled) :)

Thank you so much,But what I wanted to say is that I need a Universal render pipeline version of Animation system Not a HDRP version,Can you help me?

**Comment by nicolasgramlich** [comment]
The only thing you really need to add for "URP support" is the URP compatible shader from above :)

To make it work in your own project, copy these files to your project: https://github.com/Unity-Technologies/Unity.Animation.Samples/tree/14ece9d3c953cc32c2c0f2ae196140a4ae80455c/UnityAnimationHDRPExamples/Assets/Scripts/Common (you don't need all of them, but copy all of them for simplicity).

In order to help you need to be more specific on what's not working.

To originally get it working in my project took me more time than I'm willing to admit :)

For cross reference there is also a thread developing here: https://forum.unity.com/threads/animation-documentation.818892/#post-5472981

If I have the time, I'll fork this project and make a crude, working and highly unofficial URP example 🙈

**Comment by cdm456852** [comment]
> The only thing you really need to add for "URP support" is the URP compatible shader from above :)
> 
> To make it work in your own project, copy these files to your project: https://github.com/Unity-Technologies/Unity.Animation.Samples/tree/14ece9d3c953cc32c2c0f2ae196140a4ae80455c/UnityAnimationHDRPExamples/Assets/Scripts/Common (you don't need all of them, but copy all of them for simplicity).
> 
> In order to help you need to be more specific on what's not working.
> 
> To originally get it working in my project took me more time than I'm willing to admit :)
> 
> For cross reference there is also a thread developing here: https://forum.unity.com/threads/animation-documentation.818892/#post-5472981
> 
> If I have the time, I'll fork this project and make a crude, working and highly unofficial URP example 🙈

Thank you so much,I will try it later!!

**Comment by JCBuck** [comment]
I presume this is still an issue with instancing with skinned mesh rendering in URP.

I've ported over the simple HDRP shadergraph to URP with PBR instead and it results in these deformities.

![image](https://user-images.githubusercontent.com/5351275/74906491-326a4a00-537f-11ea-9aa5-3f57a1dcef2d.png)

funny enough even the material preview is being shifted around as the animation is running in the editor
![image](https://user-images.githubusercontent.com/5351275/74906669-ad336500-537f-11ea-9452-494ac50501d3.png)
![image](https://user-images.githubusercontent.com/5351275/74906677-b45a7300-537f-11ea-85a0-5cc459d4eedd.png)

**Comment by ulti-killer** [comment]
> Great work @nicolasgramlich ! Although I think you might be taking a performance hit because you may not go through the GPU instancing pipeline. To answer your question, we are planning on making a URP experimental skinning pipeline available around GDC. Hopefully you can put your hands on it then.
> 
> Note that we also just pushed another update (0.3.0-preview.7), this has quite a few improvements namely better dots component integration with our animation graph evaluator and a data layout that is more SIMD friendly. This should translate better performances overall.

Hi @oldio. Does URP experimental skinning pipeline optimized for mobile platform?

**Comment by segant08** [comment]
Hi i could managed to do with urp too. But currently using srp. I think gdc is near. So will gpu instancing be released with urp?

**Comment by cdm456852** [comment]
> The only thing you really need to add for "URP support" is the URP compatible shader from above :)
> 
> To make it work in your own project, copy these files to your project: https://github.com/Unity-Technologies/Unity.Animation.Samples/tree/14ece9d3c953cc32c2c0f2ae196140a4ae80455c/UnityAnimationHDRPExamples/Assets/Scripts/Common (you don't need all of them, but copy all of them for simplicity).
> 
> In order to help you need to be more specific on what's not working.
> 
> To originally get it working in my project took me more time than I'm willing to admit :)
> 
> For cross reference there is also a thread developing here: https://forum.unity.com/threads/animation-documentation.818892/#post-5472981
> 
> If I have the time, I'll fork this project and make a crude, working and highly unofficial URP example 🙈

So there is still no timeline for the dots animation support of the universal render pipeline.
I am very sad because it's been a very long time since the last time that they said they will support the urp render pipeline very soon.

**Comment by nicolasgramlich** [comment]
So I finally took a stab at this again. After almost giving up trying to find out why all the meshes were "in sync" despite having individually animating bones. It would look something like this:
![Screen Shot 2020-05-10 at 10 13 13 PM](https://user-images.githubusercontent.com/287060/81526196-d1ae3600-930b-11ea-8cc6-bb6b4290aa97.png)

Turns out all you have to do to fix it is turn on `Enable GPU Instancing` wherever you use that material:
![Screen Shot 2020-05-10 at 10 09 49 PM](https://user-images.githubusercontent.com/287060/81526265-03270180-930c-11ea-9d4c-fb6eb4104388.png)

And as you can see the problem has been solved and the meshes are now in sync with their individual bones :)

Turns out @oldio pushed that change after me cloning the repo https://github.com/Unity-Technologies/Unity.Animation.Samples/commit/dd68f2c455c227c2b273d92feb4b2896379de8c0 🙈 🙃 😱 

Note: This is all HDRP and I'll give it a shot on URP 🙏

**Comment by nicolasgramlich** [comment]
No luck with URP 😭 

@oldio any news? 🙏

**Comment by nicolasgramlich** [comment]
No luck with URP 😭 

@oldio I'm kindly asking if there any news? 🙏  (good or bad news, we can handle it)

Oh and if you could make a recommendation if we should switch to 2020.x to use this package with URP, let us know 😄

**Comment by cdm456852** [comment]
> > After dipping my toes into Shader Graph the other week, I was able to get a textured example in URP to work (literally just had to hook in that texture).
> > ![image](https://user-images.githubusercontent.com/287060/73720230-53bc0c80-46d6-11ea-8bf9-6c77b91557d5.png)
> > On my Macbook I can get ≈2500 Units to animate (simple lit, physics bodies (cylinders), no shadows, 1M triangles, SRP Batcher `disabled`, Dynamic Batching `enabled` (but doesn't seem to work)) at 30FPS in the Editor (probably some more when building the actual app)
> > ![Screen Shot 2020-02-03 at 10 38 07 PM](https://user-images.githubusercontent.com/287060/73720103-0b9cea00-46d6-11ea-8524-e67aed740407.png)
> > (Closeup with shadows enabled)
> > ![Screen Shot 2020-02-03 at 10 39 04 PM](https://user-images.githubusercontent.com/287060/73720101-0b9cea00-46d6-11ea-92c0-d9efcb427531.png)
> > Poking around in the Entity Debugger it looks like every single rig is animated separately, they just happen to be "in sync" because they start at exactly the same time.
> > ![Screen Shot 2020-02-03 at 10 38 14 PM](https://user-images.githubusercontent.com/287060/73720102-0b9cea00-46d6-11ea-93c5-d6efd16b7feb.png)
> > My machine:
> > ![image](https://user-images.githubusercontent.com/287060/73720459-d47b0880-46d6-11ea-95b8-bccdb292e3d4.png)
> > # Android
> > ## Pixel XL (2016 flagship phone)
> > 30 FPS with 400 units, simple lit, physics bodies (cylinders), no shadows
> > ![Screenshot_20200203-234938](https://user-images.githubusercontent.com/287060/73724499-5885be00-46e0-11ea-9f0b-90c738fde15b.png)
> > ## Pixel 4 XL (2019 flagship phone)
> > Going to test on this one tomorrow, but pretty sure I can get 90 FPS :)
> > Overall I'm happy with the performance :)
> 
> Great work @nicolasgramlich ! Although I think you might be taking a performance hit because you may not go through the GPU instancing pipeline. To answer your question, we are planning on making a URP experimental skinning pipeline available around GDC. Hopefully you can put your hands on it then.
> 
> Note that we also just pushed another update (0.3.0-preview.7), this has quite a few improvements namely better dots component integration with our animation graph evaluator and a data layout that is more SIMD friendly. This should translate better performances overall.

Hi, Can you share your project to me, I tried multiple times with URP, But all of them failed,I am very interested in your example with URP and texture.

**Comment by nicolasgramlich** [comment]
@oldio any news for us 🙏  :)

**Comment by Snow-Okami** [comment]
Yes, also wondering on news of URP as it has been several months now.

**Comment by cdm456852** [comment]
> Yes, also wondering on news of URP as it has been several months now.

But it seemed the author of this example did not want to care about our question Because they never reply us, And this example has not been updated for 7 months,I am very disappointed about the author of this example.

**Comment by oldio** [comment]
It's not because we do not care - that couldn't further from the truth.

The main reason for delaying updates has been mostly motivated by how unstable the code base has been these past few months and we did not want to expose our users to such churn. One point to note is that rendering aspects are not dictated by one sole team but a coordination of multiple packages working together. Fortunately we are now able create a workable URP project and one of our goals this sprint is to update these samples to add a URP project to the mix. It will at most contain only a small set of samples but the difference in setup between URP/HDRP is minimal (i.e. materials need to be recreated in the appropriate format). Unfortunately I can't promise an ETA right now but this repo should be updated soon to reflect all the work that has been done in the past few months.

**Comment by cdm456852** [comment]
> It's not because we do not care - that couldn't further from the truth.
> 
> The main reason for delaying updates has been mostly motivated by how unstable the code base has been these past few months and we did not want to expose our users to such churn. One point to note is that rendering aspects are not dictated by one sole team but a coordination of multiple packages working together. Fortunately we are now able create a workable URP project and one of our goals this sprint is to update these samples to add a URP project to the mix. It will at most contain only a small set of samples but the difference in setup between URP/HDRP is minimal (i.e. materials need to be recreated in the appropriate format). Unfortunately I can't promise an ETA right now but this repo should be updated soon to reflect all the work that has been done in the past few months.

Hi! Thanks for your reply, I am so glad to hear the news about the next release, Especially for the URP support, You said that this example will be updated soon, So Can I assume the next update will come before the end of this month?

**Comment by nicolasgramlich** [comment]
@cdm456852 he specifically said there is no ETA right now, so let's be patient hopefully just a little longer 🙏 

@oldio The community really appreciates the response. What we were "upset" about is not really the lack of "code updates" but simply updates on the general state of the package. There are delays and things always take longer (we're all just as guilty of that), but the difference is being left in the dark and an update just like the one you did "Things are taking longer. There is no ETA right now." is all we've been asking for :)

That being said, we're all very excited about the URP support, even if it's just minimal :)

**Comment by oldio** [comment]
URP project is now provided in the last sample update.

**Comment by jackylong** [comment]
niu b

**Comment by ajc-software-ltd** [comment]
com.unity.animation 0.9.0 will work with com.unity.rendering.hybrid upto 0.11.0.preview.44 and only work upto 2021.1.28f1 , I have tested 2021.2.0 it failed with a graph foundation error. 
I hope this helps people trying builds to get the animation system working.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/18106203/177958765-3dace216-9801-4167-9080-903f431893c5.png">

<img width="313" alt="image" src="https://user-images.githubusercontent.com/18106203/177958999-8f92161d-10ab-4294-98b5-51d16280cdc6.png">

advised you add ENABLE_COMPUTE_DEFORMATIONS into your project settings under player
then Go to the Unity Project's directory, open Library, and delete the ShaderCache directory
<img width="958" alt="image" src="https://user-images.githubusercontent.com/18106203/177959952-65a40ff8-e6ef-44f7-8f0d-3d32d924b378.png">
