### ISSUE TITLE
0.5.1-preview.1 - June 18, 2020

### ISSUE THREAD

**Issue by nicolasgramlich** [Unity-Technologies/Unity.Animation.Samples#15]
`0.5.1-preview.1` just dropped. Let's report on our progress/success in this issue :)

https://docs.unity3d.com/Packages/com.unity.animation@0.5/changelog/CHANGELOG.html

**Comment by khaya-kinstrife** [comment]
Great stuff! Are there any samples available?

**Comment by jlscurran** [comment]
Going a bit weirdly for me; when I try to use `clip.ToDenseClip(clip)` to make a PlayClipComponent, I get
` 'AnimationClip' does not contain a definition for 'ToDenseClip' and no accessible extension method 'ToDenseClip' accepting a first argument of type 'AnimationClip' could be found` etc.

It's the only error I get and it only happens when building; the editor is fine. Anybody know what I can do about that?
